<?php

namespace App\Filament\Resources\Ports\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class PortsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('device.device_id')
                    ->searchable(),
                TextColumn::make('port_descr_type')
                    ->searchable(),
                TextColumn::make('port_descr_descr')
                    ->searchable(),
                TextColumn::make('port_descr_circuit')
                    ->searchable(),
                TextColumn::make('port_descr_speed')
                    ->searchable(),
                TextColumn::make('port_descr_notes')
                    ->searchable(),
                TextColumn::make('ifDescr')
                    ->searchable(),
                TextColumn::make('ifName')
                    ->searchable(),
                TextColumn::make('portName')
                    ->searchable(),
                TextColumn::make('ifIndex')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifSpeed')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifSpeed_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifConnectorPresent')
                    ->searchable(),
                TextColumn::make('ifOperStatus')
                    ->searchable(),
                TextColumn::make('ifOperStatus_prev')
                    ->searchable(),
                TextColumn::make('ifAdminStatus')
                    ->searchable(),
                TextColumn::make('ifAdminStatus_prev')
                    ->searchable(),
                TextColumn::make('ifDuplex')
                    ->searchable(),
                TextColumn::make('ifMtu')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifType')
                    ->searchable(),
                TextColumn::make('ifAlias')
                    ->searchable(),
                TextColumn::make('ifPhysAddress')
                    ->searchable(),
                TextColumn::make('ifLastChange')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifVlan')
                    ->searchable(),
                TextColumn::make('ifTrunk')
                    ->searchable(),
                TextColumn::make('ifVrf')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('ignore')
                    ->boolean(),
                IconColumn::make('disabled')
                    ->boolean(),
                IconColumn::make('deleted')
                    ->boolean(),
                TextColumn::make('pagpOperationMode')
                    ->searchable(),
                TextColumn::make('pagpPortState')
                    ->searchable(),
                TextColumn::make('pagpPartnerDeviceId')
                    ->searchable(),
                TextColumn::make('pagpPartnerLearnMethod')
                    ->searchable(),
                TextColumn::make('pagpPartnerIfIndex')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('pagpPartnerGroupIfIndex')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('pagpPartnerDeviceName')
                    ->searchable(),
                TextColumn::make('pagpEthcOperationMode')
                    ->searchable(),
                TextColumn::make('pagpDeviceId')
                    ->searchable(),
                TextColumn::make('pagpGroupIfIndex')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInUcastPkts')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInUcastPkts_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInUcastPkts_delta')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInUcastPkts_rate')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutUcastPkts')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutUcastPkts_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutUcastPkts_delta')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutUcastPkts_rate')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInErrors')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInErrors_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInErrors_delta')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInErrors_rate')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutErrors')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutErrors_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutErrors_delta')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutErrors_rate')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInOctets')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInOctets_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInOctets_delta')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifInOctets_rate')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutOctets')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutOctets_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutOctets_delta')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ifOutOctets_rate')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('poll_time')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('poll_prev')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('poll_period')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
