<?php

namespace App\Filament\Resources\Devices\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class DeviceInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('inserted')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('hostname'),
                TextEntry::make('sysName')
                    ->placeholder('-'),
                TextEntry::make('display')
                    ->placeholder('-'),
                TextEntry::make('ip')
                    ->placeholder('-'),
                TextEntry::make('overwrite_ip')
                    ->placeholder('-'),
                TextEntry::make('community')
                    ->placeholder('-'),
                TextEntry::make('authlevel')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('authname')
                    ->placeholder('-'),
                TextEntry::make('authpass')
                    ->placeholder('-'),
                TextEntry::make('authalgo')
                    ->placeholder('-'),
                TextEntry::make('cryptopass')
                    ->placeholder('-'),
                TextEntry::make('cryptoalgo')
                    ->placeholder('-'),
                TextEntry::make('snmpver'),
                TextEntry::make('port')
                    ->numeric(),
                TextEntry::make('transport'),
                TextEntry::make('timeout')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('retries')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('snmp_disable')
                    ->boolean(),
                TextEntry::make('bgpLocalAs')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sysObjectID')
                    ->placeholder('-'),
                TextEntry::make('sysDescr')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('sysContact')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('version')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('hardware')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('features')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('location.id')
                    ->label('Location')
                    ->placeholder('-'),
                TextEntry::make('os')
                    ->placeholder('-'),
                IconEntry::make('status')
                    ->boolean(),
                TextEntry::make('status_reason'),
                IconEntry::make('ignore')
                    ->boolean(),
                IconEntry::make('disabled')
                    ->boolean(),
                TextEntry::make('uptime')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('agent_uptime')
                    ->numeric(),
                TextEntry::make('last_polled')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('last_poll_attempted')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('last_polled_timetaken')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('last_discovered_timetaken')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('last_discovered')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('last_ping')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('last_ping_timetaken')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('purpose')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('type'),
                TextEntry::make('serial')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('icon')
                    ->placeholder('-'),
                TextEntry::make('poller_group')
                    ->numeric(),
                IconEntry::make('override_sysLocation')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('port_association_mode')
                    ->numeric(),
                TextEntry::make('max_depth')
                    ->numeric(),
                IconEntry::make('disable_notify')
                    ->boolean(),
                IconEntry::make('ignore_status')
                    ->boolean(),
            ]);
    }
}
