<?php

namespace App\Filament\Resources\Ports\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class PortInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('device.device_id')
                    ->label('Device'),
                TextEntry::make('port_descr_type')
                    ->placeholder('-'),
                TextEntry::make('port_descr_descr')
                    ->placeholder('-'),
                TextEntry::make('port_descr_circuit')
                    ->placeholder('-'),
                TextEntry::make('port_descr_speed')
                    ->placeholder('-'),
                TextEntry::make('port_descr_notes')
                    ->placeholder('-'),
                TextEntry::make('ifDescr')
                    ->placeholder('-'),
                TextEntry::make('ifName')
                    ->placeholder('-'),
                TextEntry::make('portName')
                    ->placeholder('-'),
                TextEntry::make('ifIndex')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifSpeed')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifSpeed_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifConnectorPresent')
                    ->placeholder('-'),
                TextEntry::make('ifOperStatus')
                    ->placeholder('-'),
                TextEntry::make('ifOperStatus_prev')
                    ->placeholder('-'),
                TextEntry::make('ifAdminStatus')
                    ->placeholder('-'),
                TextEntry::make('ifAdminStatus_prev')
                    ->placeholder('-'),
                TextEntry::make('ifDuplex')
                    ->placeholder('-'),
                TextEntry::make('ifMtu')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifType')
                    ->placeholder('-'),
                TextEntry::make('ifAlias')
                    ->placeholder('-'),
                TextEntry::make('ifPhysAddress')
                    ->placeholder('-'),
                TextEntry::make('ifLastChange')
                    ->numeric(),
                TextEntry::make('ifVlan')
                    ->placeholder('-'),
                TextEntry::make('ifTrunk')
                    ->placeholder('-'),
                TextEntry::make('ifVrf')
                    ->numeric(),
                IconEntry::make('ignore')
                    ->boolean(),
                IconEntry::make('disabled')
                    ->boolean(),
                IconEntry::make('deleted')
                    ->boolean(),
                TextEntry::make('pagpOperationMode')
                    ->placeholder('-'),
                TextEntry::make('pagpPortState')
                    ->placeholder('-'),
                TextEntry::make('pagpPartnerDeviceId')
                    ->placeholder('-'),
                TextEntry::make('pagpPartnerLearnMethod')
                    ->placeholder('-'),
                TextEntry::make('pagpPartnerIfIndex')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pagpPartnerGroupIfIndex')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pagpPartnerDeviceName')
                    ->placeholder('-'),
                TextEntry::make('pagpEthcOperationMode')
                    ->placeholder('-'),
                TextEntry::make('pagpDeviceId')
                    ->placeholder('-'),
                TextEntry::make('pagpGroupIfIndex')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInUcastPkts')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInUcastPkts_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInUcastPkts_delta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInUcastPkts_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutUcastPkts')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutUcastPkts_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutUcastPkts_delta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutUcastPkts_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInErrors')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInErrors_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInErrors_delta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInErrors_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutErrors')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutErrors_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutErrors_delta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutErrors_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInOctets')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInOctets_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInOctets_delta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifInOctets_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutOctets')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutOctets_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutOctets_delta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('ifOutOctets_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('poll_time')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('poll_prev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('poll_period')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
