<?php

namespace App\Filament\Resources\Ports\Schemas;

use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class PortForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('device_id')
                    ->relationship('device', 'device_id')
                    ->required()
                    ->default(0),
                TextInput::make('port_descr_type')
                    ->default(null),
                TextInput::make('port_descr_descr')
                    ->default(null),
                TextInput::make('port_descr_circuit')
                    ->default(null),
                TextInput::make('port_descr_speed')
                    ->default(null),
                TextInput::make('port_descr_notes')
                    ->default(null),
                TextInput::make('ifDescr')
                    ->default(null),
                TextInput::make('ifName')
                    ->default(null),
                TextInput::make('portName')
                    ->default(null),
                TextInput::make('ifIndex')
                    ->numeric()
                    ->default(0),
                TextInput::make('ifSpeed')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifSpeed_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifConnectorPresent')
                    ->default(null),
                TextInput::make('ifOperStatus')
                    ->default(null),
                TextInput::make('ifOperStatus_prev')
                    ->default(null),
                TextInput::make('ifAdminStatus')
                    ->default(null),
                TextInput::make('ifAdminStatus_prev')
                    ->default(null),
                TextInput::make('ifDuplex')
                    ->default(null),
                TextInput::make('ifMtu')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifType')
                    ->default(null),
                TextInput::make('ifAlias')
                    ->default(null),
                TextInput::make('ifPhysAddress')
                    ->default(null),
                TextInput::make('ifLastChange')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ifVlan')
                    ->default(null),
                TextInput::make('ifTrunk')
                    ->default(null),
                TextInput::make('ifVrf')
                    ->required()
                    ->numeric()
                    ->default(0),
                Toggle::make('ignore')
                    ->required(),
                Toggle::make('disabled')
                    ->required(),
                Toggle::make('deleted')
                    ->required(),
                TextInput::make('pagpOperationMode')
                    ->default(null),
                TextInput::make('pagpPortState')
                    ->default(null),
                TextInput::make('pagpPartnerDeviceId')
                    ->default(null),
                TextInput::make('pagpPartnerLearnMethod')
                    ->default(null),
                TextInput::make('pagpPartnerIfIndex')
                    ->numeric()
                    ->default(null),
                TextInput::make('pagpPartnerGroupIfIndex')
                    ->numeric()
                    ->default(null),
                TextInput::make('pagpPartnerDeviceName')
                    ->default(null),
                TextInput::make('pagpEthcOperationMode')
                    ->default(null),
                TextInput::make('pagpDeviceId')
                    ->default(null),
                TextInput::make('pagpGroupIfIndex')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInUcastPkts')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInUcastPkts_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInUcastPkts_delta')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInUcastPkts_rate')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutUcastPkts')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutUcastPkts_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutUcastPkts_delta')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutUcastPkts_rate')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInErrors')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInErrors_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInErrors_delta')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInErrors_rate')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutErrors')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutErrors_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutErrors_delta')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutErrors_rate')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInOctets')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInOctets_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInOctets_delta')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifInOctets_rate')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutOctets')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutOctets_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutOctets_delta')
                    ->numeric()
                    ->default(null),
                TextInput::make('ifOutOctets_rate')
                    ->numeric()
                    ->default(null),
                TextInput::make('poll_time')
                    ->numeric()
                    ->default(null),
                TextInput::make('poll_prev')
                    ->numeric()
                    ->default(null),
                TextInput::make('poll_period')
                    ->numeric()
                    ->default(null),
            ]);
    }
}
